### ISSUE TITLE
启动不了

### ISSUE THREAD

**Issue by yeyue1992** [PLQin/vue-vant-template#3]
Unca
![2FA9C6EC-5444-4d59-A7DC-4C16CB728609](https://user-images.githubusercontent.com/36325990/104835748-a5f43e80-58e3-11eb-8a8d-35277f26d2a1.png)
ught Error: Cannot find module './en_us.json'

**Comment by PLQin** [comment]
感谢提醒，已经处理好了，请重试：

```
git clone https://github.com/PLQin/vue-vant-template.git --depth=1
```
